blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/2025-OSDC/colbrush/discussions
    about: Ask questions or discuss ideas with the community
  - name: Documentation
    url: https://www.colbrush.site
    about: Visit our documentation website
